/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package line_bot

import kotlin.test.Test
import kotlin.test.assertEquals

class AppTest {
    @Test fun testAppHasAGreeting() {
        assertEquals(echoMessage("a"), "a")
    }
}
